export const products = [
  {
    image: "orange-suit_xn4csv",
    title: "Orange Swimsuit II",
    cost: 120,
    quantity: 5,
    category: "Ladies",
    description:
      "Stylish and comfortable orange swimsuit for a day at the beach.",
    galleryImages: ["orange-suit_xn4csv", "beach-dress-turquoise_shkcqo"],
    colors: [
      { name: "Orange", hexcode: "#FFA500" },
      { name: "Red", hexcode: "#FF0000" },
    ],
    sizes: ["S", "M", "L"],
    brand: "BeachWear Co.",
    tags: "swimsuit, beach, summer",
  },
  {
    image: "beach-dress-white_epsfxy",
    title: "Turquoise Beach Dress II",
    cost: 80,
    quantity: 3,
    category: "Ladies",
    description: "Lightweight turquoise beach dress for a breezy summer look.",
    galleryImages: ["beach-dress-white_epsfxy", "floral-bikini_xaylmc"],
    colors: [
      { name: "Turquoise", hexcode: "#40E0D0" },
      { name: "White", hexcode: "#FFFFFF" },
    ],
    sizes: ["M", "L"],
    brand: "Tropical Vibes",
    tags: "dress, beach, summer",
  },
  {
    image: "floral-bikini_xaylmc",
    title: "Floral Bikini Set II",
    cost: 95,
    quantity: 10,
    category: "Ladies",
    description: "Trendy floral bikini set, perfect for vacations.",
    galleryImages: ["floral-bikini_xaylmc", "swimsuit._iarjd7"],
    colors: [
      { name: "Multicolor", hexcode: "#FF69B4" },
      { name: "Yellow", hexcode: "#FFFF00" },
    ],
    sizes: ["XS", "S", "M"],
    brand: "Sun & Sand",
    tags: "swimsuit, bikini, summer",
  },
  {
    image: "beach-dress-white_epsfxy",
    title: "White Beach Dress II",
    cost: 90,
    quantity: 4,
    category: "Ladies",
    description: "Elegant white dress perfect for a beach getaway.",
    galleryImages: ["beach-dress-white_epsfxy", "beach-dress-turquoise_shkcqo"],
    colors: [
      { name: "White", hexcode: "#FFFFFF" },
      { name: "Blue", hexcode: "#0000FF" },
    ],
    sizes: ["S", "M", "L", "XL"],
    brand: "Seaside Chic",
    tags: "swimsuit, beach, dress",
  },
  {
    image: "beach-dress-turquoise_shkcqo",
    title: "Black Swimsuit II",
    cost: 110,
    quantity: 6,
    category: "Ladies",
    description: "Classic black swimsuit with a sleek fit.",
    galleryImages: ["beach-dress-turquoise_shkcqo", "orange-suit_xn4csv"],
    colors: [
      { name: "Black", hexcode: "#000000" },
      { name: "Gray", hexcode: "#808080" },
    ],
    sizes: ["M", "L", "XL"],
    brand: "Wave Riders",
    tags: "swimsuit, beach, pool",
  },
  {
    image: "swimsuit._iarjd7",
    title: "Chic One-Piece Swimsuit II",
    cost: 130,
    quantity: 7,
    category: "Ladies",
    description: "Sophisticated one-piece swimsuit for a trendy beach day.",
    galleryImages: ["swimsuit._iarjd7", "floral-bikini_xaylmc"],
    colors: [
      { name: "Navy Blue", hexcode: "#000080" },
      { name: "Purple", hexcode: "#800080" },
    ],
    sizes: ["S", "M", "L"],
    brand: "Ocean Glam",
    tags: "swimsuit, beach, fashion",
  },
  {
    image: "floral-bikini_xaylmc",
    title: "Floral Bikini - Limited Edition II",
    cost: 105,
    quantity: 8,
    category: "Ladies",
    description: "A special edition floral bikini for summer vibes.",
    galleryImages: ["floral-bikini_xaylmc", "swimsuit._iarjd7"],
    colors: [
      { name: "Pink", hexcode: "#FFC0CB" },
      { name: "Green", hexcode: "#008000" },
    ],
    sizes: ["XS", "S", "M", "L"],
    brand: "Tropical Bliss",
    tags: "swimsuit, beach, fashion",
  },
  {
    image: "beach-dress-white_epsfxy",
    title: "Turquoise Sundress II",
    cost: 85,
    quantity: 9,
    category: "Ladies",
    description: "Casual sundress in a refreshing turquoise shade.",
    galleryImages: ["beach-dress-white_epsfxy", "beach-dress-turquoise_shkcqo"],
    colors: [
      { name: "Turquoise", hexcode: "#40E0D0" },
      { name: "Coral", hexcode: "#FF7F50" },
    ],
    sizes: ["M", "L", "XL"],
    brand: "Sea Breeze",
    tags: "casual, dress, summer",
  },
  {
    image: "orange-suit_xn4csv",
    title: "Vibrant Orange Swimsuit II",
    cost: 125,
    quantity: 6,
    category: "Ladies",
    description: "Stand out in this eye-catching orange swimsuit.",
    galleryImages: ["orange-suit_xn4csv", "beach-dress-turquoise_shkcqo"],
    colors: [
      { name: "Orange", hexcode: "#FFA500" },
      { name: "Teal", hexcode: "#008080" },
    ],
    sizes: ["S", "M", "L", "XL"],
    brand: "Sunshine Wear",
    tags: "swimsuit, beach, fashion",
  },
  {
    image: "beach-dress-turquoise_shkcqo",
    title: "Black Cut-Out Swimsuit II",
    cost: 135,
    quantity: 5,
    category: "Ladies",
    description: "Elegant black swimsuit with modern cut-out details.",
    galleryImages: ["beach-dress-turquoise_shkcqo", "swimsuit._iarjd7"],
    colors: [
      { name: "Black", hexcode: "#000000" },
      { name: "Burgundy", hexcode: "#800020" },
    ],
    sizes: ["S", "M", "L"],
    brand: "Luxury Swim",
    tags: "swimsuit, beach, pool",
  },
];
