export const users = [
  {
    email: "jordanlake18@outlook.com",
    password: "Admin123!",
    firstName: "Admin",
    lastName: "Admin",
    city: "Arima",
    street: "1 Picton Lane",
    phone: "737-3857",
    isAdmin: true,
  },
  {
    email: "lakejordan54@gmail.com",
    password: "Test123!",
    firstName: "Test",
    lastName: "User",
    city: "Arima",
    phone: "737-3857",
    street: "1 Picton Lane",
  },
  {
    email: "iamprobablynot@live.com",
    password: "Test123!",
    firstName: "Test2",
    lastName: "User2",
    city: "Arima",
    phone: "737-3857",
    street: "1 Picton Lane",
  },
];
