export const users = [
  {
    email: "thedivingblock@gmail.com",
    password: "Jamila21!",
    firstName: "Jamila",
    lastName: "DivingBlock",
    city: "Port of Spain",
    street: "Henry",
    phone: "314-3157",
    isAdmin: true,
  },
  {
    email: "jordanlake18@outlook.com",
    password: "jfw+U=<33Q",
    firstName: "Jamila",
    lastName: "DivingBlock",
    city: "Port of Spain",
    street: "Henry",
    phone: "314-3157",
    isAdmin: true,
  },
  {
    email: "lakejordan54@gmail.com",
    password: "Test123!",
    firstName: "Test",
    lastName: "User",
    city: "Arima",
    phone: "737-3857",
    street: "1 Picton Lane",
  },
  {
    email: "iamprobablynot@live.com",
    password: "Test123!",
    firstName: "Test2",
    lastName: "User2",
    city: "Arima",
    phone: "737-3857",
    street: "1 Picton Lane",
  },
];
